export const LABS = [
  { id: '1', title: 'AWS Advanced Architecting', logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg' },
  { id: '2', title: 'Invinsense', logo: 'https://picsum.photos/seed/invinsense/200/200' },
  { id: '3', title: 'Linux', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg' },
  { id: '4', title: 'Python', logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg' },
  { id: '5', title: 'DBMS', logo: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Sql_data_base_with_logo.png' },
  { id: '6', title: 'Java', logo: 'https://upload.wikimedia.org/wikipedia/en/3/30/Java_programming_language_logo.svg' },
];
export const SUB_LABS_DATA = {
  'AWS Advanced Architecting': [
    { id: 's1', title: 'Building with Amazon Bedrock', logo: 'https://picsum.photos/seed/bedrock/200/200', duration: '120 Minutes', credits: 50, rating: 0 },
    { id: 's2', title: 'AWS Route 53 Resolver', logo: 'https://picsum.photos/seed/route53/200/200', duration: '180 Minutes', credits: 60, rating: 2.5 },
    { id: 's3', title: 'AWS S3 Private Access with VPC Endpoints', logo: 'https://picsum.photos/seed/s3vpc/200/200', duration: '120 Minutes', credits: 60, rating: 5 },
    { id: 's4', title: 'Active Directory SAML Integration Lab', logo: 'https://picsum.photos/seed/ad/200/200', duration: '120 Minutes', credits: 60, rating: 0 },
    { id: 's5', title: 'AWS IoT Greengrass V2', logo: 'https://picsum.photos/seed/iot/200/200', duration: '180 Minutes', credits: 500, rating: 0 },
    { id: 's6', title: 'AWS Client VPN Hands-On Lab', logo: 'https://picsum.photos/seed/vpn/200/200', duration: '120 Minutes', credits: 60, rating: 4.5 },
    { id: 's7', title: 'AWS Lake formation', logo: 'https://picsum.photos/seed/lake/200/200', duration: '120 Minutes', credits: 90, rating: 5 },
    { id: 's8', title: 'AWS Hybrid Connectivity with Managed VPN', logo: 'https://picsum.photos/seed/hybrid/200/200', duration: '180 Minutes', credits: 60, rating: 4.8 },
    { id: 's9', title: 'AWS Database Migration Lab', logo: 'https://picsum.photos/seed/db/200/200', duration: '180 Minutes', credits: 180, rating: 0 },
    { id: 's10', title: 'AWS Sandbox', logo: 'https://picsum.photos/seed/sandbox/200/200', duration: '120 Minutes', credits: 30, rating: 3.7 },
  ],
  'Invinsense': [
    { id: 'i1', title: 'Shuffle Automation', logo: 'https://picsum.photos/seed/shuffle/200/200', duration: '120 Minutes', credits: 50, rating: 5 },
    { id: 'i2', title: 'Misp Threat Sharing', logo: 'https://picsum.photos/seed/misp/200/200', duration: '60 Minutes', credits: 32, rating: 0 },
    { id: 'i3', title: 'CALDERA', logo: 'https://picsum.photos/seed/caldera/200/200', duration: '120 Minutes', credits: 50, rating: 0 },
    { id: 'i4', title: 'Wazuh', logo: 'https://picsum.photos/seed/wazuh/200/200', duration: '60 Minutes', credits: 40, rating: 5 },
    { id: 'i5', title: 'DefectDojo', logo: 'https://picsum.photos/seed/defectdojo/200/200', duration: '120 Minutes', credits: 50, rating: 0 },
    { id: 'i6', title: 'Invinsense XDR', logo: 'https://picsum.photos/seed/xdr/200/200', duration: '60 Minutes', credits: 50, rating: 4 },
    { id: 'i7', title: 'Thehive & Cortex', logo: 'https://picsum.photos/seed/cortex/200/200', duration: '60 Minutes', credits: 40, rating: 0 },
  ],
  'Linux': [
    { id: 'l1', title: 'Basic Mail Server Setup (Postfix)', logo: 'https://picsum.photos/seed/postfix/200/200', duration: '60 Minutes', credits: 30, rating: 0 },
    { id: 'l2', title: 'Access Systems And Obtaining Support', logo: 'https://picsum.photos/seed/support/200/200', duration: '30 Minutes', credits: 0, rating: 4.7, isFree: true },
    { id: 'l3', title: 'Tomcat With One Sample Jar File Remote Using Maven', logo: 'https://picsum.photos/seed/tomcat/200/200', duration: '60 Minutes', credits: 25, rating: 0 },
    { id: 'l4', title: 'Centos 8', logo: 'https://picsum.photos/seed/centos/200/200', duration: '30 Minutes', credits: 0, rating: 4, isFree: true },
    { id: 'l5', title: 'Linux Directories and File Permissions', logo: 'https://picsum.photos/seed/dirs/200/200', duration: '60 Minutes', credits: 0, rating: 4.2, isFree: true },
    { id: 'l6', title: 'Nodejs Latest With Angular', logo: 'https://picsum.photos/seed/angular/200/200', duration: '60 Minutes', credits: 30, rating: 0 },
    { id: 'l7', title: 'Wordpress On Single Server', logo: 'https://picsum.photos/seed/wp/200/200', duration: '60 Minutes', credits: 25, rating: 0 },
    { id: 'l8', title: 'Ubuntu Grade', logo: 'https://picsum.photos/seed/ubuntu/200/200', duration: '5760 Minutes', credits: 1000, rating: 0 },
    { id: 'l9', title: 'Samba Active Directory', logo: 'https://picsum.photos/seed/samba/200/200', duration: '150 Minutes', credits: 40, rating: 3 },
    { id: 'l10', title: 'Shell Script Tutorial 1-2 Of 16', logo: 'https://picsum.photos/seed/shell/200/200', duration: '30 Minutes', credits: 31, rating: 0 },
    { id: 'l11', title: 'MariaDB/MySQL Fundamental', logo: 'https://picsum.photos/seed/mariadb/200/200', duration: '120 Minutes', credits: 35, rating: 0 },
    { id: 'l12', title: 'Linux Grade Test', logo: 'https://picsum.photos/seed/test/200/200', duration: '120 Minutes', credits: 30, rating: 0 },
    { id: 'l13', title: 'Nginx With Php-Fpm Using Tcp/Ip Socket', logo: 'https://picsum.photos/seed/nginx/200/200', duration: '60 Minutes', credits: 30, rating: 0 },
    { id: 'l14', title: 'Ssl/Tls Setup On Multiple Websites', logo: 'https://picsum.photos/seed/ssl/200/200', duration: '60 Minutes', credits: 25, rating: 0 },
    { id: 'l15', title: 'MySQL Fundamentals', logo: 'https://picsum.photos/seed/mysql/200/200', duration: '120 Minutes', credits: 30, rating: 0 },
    { id: 'l16', title: 'Multiple Website Hosting On Single Server', logo: 'https://picsum.photos/seed/hosting/200/200', duration: '60 Minutes', credits: 35, rating: 0 },
    { id: 'l17', title: 'Wordpress On One Webserver And One Database Server', logo: 'https://picsum.photos/seed/wpdb/200/200', duration: '60 Minutes', credits: 35, rating: 0 },
    { id: 'l18', title: 'Nfs File Sharing Server/Client Setup', logo: 'https://picsum.photos/seed/nfs/200/200', duration: '60 Minutes', credits: 30, rating: 0 },
    { id: 'l19', title: 'Workshop Demo', logo: 'https://picsum.photos/seed/workshop/200/200', duration: '10 Minutes', credits: 20, rating: 0 },
    { id: 'l20', title: 'Introduction To Linux Gui 20', logo: 'https://picsum.photos/seed/gui/200/200', duration: '30 Minutes', credits: 0, rating: 4.8, isFree: true },
    { id: 'l21', title: 'Opensuse', logo: 'https://picsum.photos/seed/suse/200/200', duration: '60 Minutes', credits: 25, rating: 4 },
    { id: 'l22', title: 'Wordpress', logo: 'https://picsum.photos/seed/wordpress/200/200', duration: '60 Minutes', credits: 25, rating: 0 },
    { id: 'l23', title: 'Samba File Server', logo: 'https://picsum.photos/seed/sambafs/200/200', duration: '60 Minutes', credits: 30, rating: 0 },
    { id: 'l24', title: 'Nodejs Latest With Pm2', logo: 'https://picsum.photos/seed/pm2/200/200', duration: '60 Minutes', credits: 30, rating: 0 },
    { id: 'l25', title: 'Basic MySQL Commands In Linux', logo: 'https://picsum.photos/seed/mysqlcmd/200/200', duration: '60 Minutes', credits: 25, rating: 0 },
    { id: 'l26', title: 'MySQL Database Fundamentals', logo: 'https://picsum.photos/seed/mysqldb/200/200', duration: '180 Minutes', credits: 25, rating: 0 },
    { id: 'l27', title: 'Linux User Management', logo: 'https://picsum.photos/seed/usermgmt/200/200', duration: '120 Minutes', credits: 0, rating: 5, isFree: true },
  ],
  'Python': [
    { id: 'p1', title: 'Python Basics and Syntax', logo: 'https://picsum.photos/seed/python-basics/200/200', duration: '60 Minutes', credits: 20, rating: 4.8 },
    { id: 'p2', title: 'Functions and Modules in Python', logo: 'https://picsum.photos/seed/python-functions/200/200', duration: '90 Minutes', credits: 25, rating: 4.5 },
    { id: 'p3', title: 'Object-Oriented Programming in Python', logo: 'https://picsum.photos/seed/python-oop/200/200', duration: '120 Minutes', credits: 35, rating: 4.7 },
    { id: 'p4', title: 'Python File Handling and Exceptions', logo: 'https://picsum.photos/seed/python-files/200/200', duration: '75 Minutes', credits: 20, rating: 4.3 },
    { id: 'p5', title: 'Python for Data Analysis', logo: 'https://picsum.photos/seed/python-data/200/200', duration: '150 Minutes', credits: 40, rating: 4.9 },
  ],
  'DBMS': [
    { id: 'd1', title: 'Introduction to DBMS', logo: 'https://picsum.photos/seed/dbms-intro/200/200', duration: '45 Minutes', credits: 15, rating: 4.4 },
    { id: 'd2', title: 'ER Diagrams and Schema Design', logo: 'https://picsum.photos/seed/dbms-er/200/200', duration: '90 Minutes', credits: 25, rating: 4.6 },
    { id: 'd3', title: 'Normalization in Databases', logo: 'https://picsum.photos/seed/dbms-normalization/200/200', duration: '75 Minutes', credits: 20, rating: 4.5 },
    { id: 'd4', title: 'SQL Queries and Joins', logo: 'https://picsum.photos/seed/dbms-sql/200/200', duration: '120 Minutes', credits: 30, rating: 4.8 },
    { id: 'd5', title: 'Transactions and Concurrency Control', logo: 'https://picsum.photos/seed/dbms-transactions/200/200', duration: '100 Minutes', credits: 30, rating: 4.2 },
  ],
  'Java': [
    { id: 'j1', title: 'Java Fundamentals', logo: 'https://picsum.photos/seed/java-fundamentals/200/200', duration: '60 Minutes', credits: 20, rating: 4.6 },
    { id: 'j2', title: 'Classes and Objects in Java', logo: 'https://picsum.photos/seed/java-oop/200/200', duration: '90 Minutes', credits: 25, rating: 4.7 },
    { id: 'j3', title: 'Java Collections Framework', logo: 'https://picsum.photos/seed/java-collections/200/200', duration: '120 Minutes', credits: 35, rating: 4.5 },
    { id: 'j4', title: 'Exception Handling in Java', logo: 'https://picsum.photos/seed/java-exceptions/200/200', duration: '75 Minutes', credits: 20, rating: 4.3 },
    { id: 'j5', title: 'JDBC and Database Connectivity', logo: 'https://picsum.photos/seed/java-jdbc/200/200', duration: '120 Minutes', credits: 35, rating: 4.8 },
  ],
};
