const fs = require('fs');
let h = fs.readFileSync('src/components/Header.tsx', 'utf8');
h = h.replace(/component=\s*header/g, 'component="header"');
h = h.replace(/className=app-shell sticky top-0 z-50 px-4 md:px-8 lg:px-10 py-3 md:py-4 border-b border-rose-100/g, 'className="app-shell sticky top-0 z-50 px-4 md:px-8 lg:px-10 py-3 md:py-4 border-b border-rose-100"');
h = h.replace(/<div className=flex items-center justify-between gap-3 md:gap-6 w-full>/g, '<div className="flex items-center justify-between gap-3 md:gap-6 w-full">');
h = h.replace(/<div className=flex items-center gap-3 md:gap-4 min-w-0>/g, '<div className="flex items-center gap-3 md:gap-4 min-w-0">');
h = h.replace(/className=md:hidden bg-ignito-maroon\/20 text-ignito-maroon hover:bg-ignito-maroon\/40/g, 'className="md:hidden bg-ignito-maroon/20 text-ignito-maroon hover:bg-ignito-maroon/40"');
h = h.replace(/size=small/g, 'size="small"');
h = h.replace(/<div className=rounded-2xl px-3 py-1 glass-panel flex items-center gap-2>/g, '<div className="rounded-2xl px-3 py-1 glass-panel flex items-center gap-2">');
h = h.replace(/<img src=\/assets\/logo.png alt=VLabs className=h-7 w-7 object-contain \/>/g, '<img src="/assets/logo.png" alt="VLabs" className="h-7 w-7 object-contain" />');
h = h.replace(/<Typography variant=subtitle2 className=font-black text-ignito-maroon tracking-tight text-sm truncate>/g, '<Typography variant="subtitle2" className="font-black text-ignito-maroon tracking-tight text-sm truncate">');
h = h.replace(/<Typography variant=body2 className=hidden md:inline-block ml-2 text-rose-600 font-semibold text-sm uppercase tracking-\[0.15em\]>/g, '<Typography variant="body2" className="hidden md:inline-block ml-2 text-rose-600 font-semibold text-sm uppercase tracking-[0.15em]">');
h = h.replace(/<div className=flex items-center gap-3 md:gap-4>/g, '<div className="flex items-center gap-3 md:gap-4">');
h = h.replace(/placeholder=Find labs users policies.../g, 'placeholder="Find labs users policies..."');
h = h.replace(/variant=outlined/g, 'variant="outlined"');
h = h.replace(/className=hidden md:flex w-\[180px\] lg:w-\[320px\]/g, 'className="hidden md:flex w-[180px] lg:w-[320px]"');
h = h.replace(/<MdSearch size={18} className=text-rose-500 \/>/g, '<MdSearch size={18} className="text-rose-500" />');
h = h.replace(/<IconButton className=flex md:hidden text-rose-600 size=small>/g, '<IconButton className="flex md:hidden text-rose-600" size="small">');
h = h.replace(/className=flex items-center gap-2 py-1 px-2 rounded-2xl border border-rose-100 bg-white\/90 shadow-sm cursor-pointer hover:shadow-md transition-all/g, 'className="flex items-center gap-2 py-1 px-2 rounded-2xl border border-rose-100 bg-white/90 shadow-sm cursor-pointer hover:shadow-md transition-all"');
h = h.replace(/<Avatar className=w-8 h-8 md:w-9 md:h-9 bg-ignito-maroon border-2 border-white text-white>/g, '<Avatar className="w-8 h-8 md:w-9 md:h-9 bg-ignito-maroon border-2 border-white text-white">');
h = h.replace(/<div className=hidden lg:block text-left>/g, '<div className="hidden lg:block text-left">');
h = h.replace(/<Typography variant=body2 className=font-bold text-gray-700 leading-none>/g, '<Typography variant="body2" className="font-bold text-gray-700 leading-none">');
h = h.replace(/<Typography variant=caption className=text-rose-500 uppercase tracking-widest text-\[10px\]>/g, '<Typography variant="caption" className="text-rose-500 uppercase tracking-widest text-[10px]">');
h = h.replace(/<div className=p-8 text-center bg-gradient-to-b from-white to-white rounded-t-\[24px\]>/g, '<div className="p-8 text-center bg-gradient-to-b from-white to-white rounded-t-[24px]">');
h = h.replace(/<div className=relative inline-block>/g, '<div className="relative inline-block">');
h = h.replace(/<Avatar className=w-24 h-24 bg-ignito-maroon mx-auto mb-4 border-4 border-white shadow-xl text-3xl font-black>/g, '<Avatar className="w-24 h-24 bg-ignito-maroon mx-auto mb-4 border-4 border-white shadow-xl text-3xl font-black">');
h = h.replace(/<div className=absolute bottom-4 right-0 w-6 h-6 bg-green-500 border-4 border-white rounded-full shadow-sm \/>/g, '<div className="absolute bottom-4 right-0 w-6 h-6 bg-green-500 border-4 border-white rounded-full shadow-sm" />');
h = h.replace(/<Typography variant=h6 className=font-black text-gray-900 mb-1 tracking-tight>/g, '<Typography variant="h6" className="font-black text-gray-900 mb-1 tracking-tight">');
h = h.replace(/<Typography variant=body2 className=text-gray-500 font-bold text-xs uppercase tracking-widest>/g, '<Typography variant="body2" className="text-gray-500 font-bold text-xs uppercase tracking-widest">');
h = h.replace(/<div className=p-6 pt-2 flex flex-col gap-3>/g, '<div className="p-6 pt-2 flex flex-col gap-3">');
h = h.replace(/variant=contained/g, 'variant="contained"');
h = h.replace(/className=!bg-ignito-maroon hover:!bg-ignito-red text-white rounded-2xl py-3 normal-case font-black text-sm shadow-lg shadow-ignito-maroon\/20 transition-all active:scale-\[0.98\]/g, 'className="!bg-ignito-maroon hover:!bg-ignito-red text-white rounded-2xl py-3 normal-case font-black text-sm shadow-lg shadow-ignito-maroon/20 transition-all active:scale-[0.98]"');
h = h.replace(/<div className=grid grid-cols-2 gap-3 mt-1>/g, '<div className="grid grid-cols-2 gap-3 mt-1">');
h = h.replace(/className=border-rose-100 text-gray-700 hover:bg-rose-50 hover:text-ignito-maroon rounded-2xl py-2 normal-case font-bold text-\[11px\] transition-all/g, 'className="border-rose-100 text-gray-700 hover:bg-rose-50 hover:text-ignito-maroon rounded-2xl py-2 normal-case font-bold text-[11px] transition-all"');
fs.writeFileSync('src/components/Header.tsx', h);
console.log("Done");
